apiVersion: v1
kind: Service
metadata:
  name: accountservice-ingress
spec:
  type: NodePort 
  ports:
  - port: 8080
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: accountservice-ingress
