apiVersion: v1
kind: Service
metadata:
  name: crudapp
spec:
  type: NodePort 
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
    nodePort: 30002
  selector:
    app: crudapp
