apiVersion: v1
kind: Service
metadata:
  name: crudapp
  namespace: default
  labels:
    app: crudapp
spec:
  type: NodePort 
  ports:
  - name: crudapp
    port: 3001
    targetPort: 3001
    protocol: TCP
    nodePort: 30002
  selector:
    app: crudapp
