apiVersion: v1
kind: Service
metadata:
  name: crudapp
  namespace: default
  labels:
    app: crudapp
spec:
  type: NodePort 
  ports:
  - name: crudapp
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30002
  selector:
    app: crudapp
